dist: trusty

language: go
go:
  - "1.11.x"

jobs:
  include:
  - if: (type = pull_request) OR (type = push AND branch = master)
    script: make checks && 
            bash <(curl -s https://codecov.io/bash)
  - if: tag IS present
    script: make checks && 
            bash <(curl -s https://codecov.io/bash) && 
            make release
